# Generated by Django 4.2.23 on 2025-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=10)),
                ('ac_client_hash', models.CharField(max_length=50)),
                ('c_txn_dt', models.DateTimeField()),
                ('txn_cod_type_rk', models.IntegerField()),
                ('txn_cod_type_name', models.CharField(max_length=200)),
                ('c_txn_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pmnt_payer_name', models.CharField(max_length=200)),
                ('day_part', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_client_hash', models.CharField(max_length=50)),
                ('eventaction', models.CharField(max_length=100)),
                ('geolatitude', models.FloatField()),
                ('geolongitude', models.FloatField()),
                ('dt', models.DateTimeField()),
                ('date_part', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_client_hash', models.CharField(max_length=50)),
                ('debt_due_bal_ccy_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_due_bal_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_overdue_bal_ccy_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_overdue_bal_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_intr_overdue_bal_ccy_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_intr_overdue_bal_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_tot_os_ccy_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_tot_os_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('overdue_duration_days', models.IntegerField()),
                ('debt_os_max_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_ovrd_max_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ovrd_max_dur_days', models.IntegerField()),
                ('ovrd_tot_ever_days', models.IntegerField()),
                ('ovrd_tot_entr_ever_qty', models.IntegerField()),
                ('ovrd_max_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_overdue_duration_days', models.IntegerField()),
                ('ovrd_tot_period_qty', models.IntegerField()),
                ('ovrd_intr_bal_max_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ovrd_intr_nobal_max_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_overdue_intr_bal_duration_days', models.IntegerField()),
                ('total_overdue_intr_nobal_duration_days', models.IntegerField()),
                ('overdue_bucket_id', models.IntegerField()),
                ('overdue_bucket_name', models.CharField(max_length=50)),
                ('npl_nflag', models.BooleanField()),
                ('day_part', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='So',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_client_hash', models.CharField(max_length=50)),
                ('erib_id', models.CharField(max_length=100)),
                ('oper_rur_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('login_type', models.CharField(max_length=50)),
                ('oper_type', models.CharField(max_length=50)),
                ('date_time_oper', models.DateTimeField()),
                ('date_create', models.DateField()),
                ('date_time_create', models.DateTimeField()),
                ('doc_type', models.CharField(max_length=50)),
                ('receiver_client_hash', models.CharField(blank=True, max_length=50, null=True)),
                ('t_p2p_flg', models.BooleanField()),
                ('day_part', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=10)),
                ('ac_client_hash', models.CharField(max_length=50)),
                ('c_txn_dt', models.DateTimeField()),
                ('txn_cod_type_rk', models.IntegerField()),
                ('txn_cod_type_name', models.CharField(max_length=200)),
                ('c_txn_rub_amt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pmnt_payer_name', models.CharField(max_length=200)),
                ('day_part', models.DateField()),
            ],
        ),
    ]
