# Generated by Django 4.2.23 on 2025-08-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='so',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tr',
            options={'managed': False},
        ),
    ]
