# Generated by Django 4.2.23 on 2025-08-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_c_options_alter_cs_options_alter_dog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='c',
            table='c',
        ),
        migrations.AlterModelTable(
            name='cs',
            table='cs',
        ),
        migrations.AlterModelTable(
            name='dog',
            table='dog',
        ),
        migrations.AlterModelTable(
            name='so',
            table='so',
        ),
        migrations.AlterModelTable(
            name='tr',
            table='tr',
        ),
    ]
