# Generated by Django 4.2.23 on 2025-08-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_c_table_alter_cs_table_alter_dog_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={},
        ),
    ]
