# Generated by Django 4.2.23 on 2025-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='ac_client_hash',
            field=models.BigIntegerField(db_column='ac_client_hash'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='dog',
            table=None,
        ),
    ]
