# Generated by Django 4.2.23 on 2025-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dog_ac_client_hash_alter_dog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCity',
            fields=[
                ('ac_client_hash', models.BigIntegerField(db_column='ac_client_hash', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
            ],
            options={
                'db_table': 'clients_city',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'managed': False},
        ),
    ]
