# Generated by Django 4.2.23 on 2025-08-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientcity_alter_dog_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='dog',
        ),
    ]
