# Generated by Django 4.2.23 on 2025-08-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='c',
            table='cber_schema.c',
        ),
        migrations.AlterModelTable(
            name='clientcity',
            table='cber_schema.clients_city',
        ),
        migrations.AlterModelTable(
            name='cs',
            table='cber_schema.cs',
        ),
        migrations.AlterModelTable(
            name='dog',
            table='cber_schema.core_dog',
        ),
        migrations.AlterModelTable(
            name='so',
            table='cber_schema.so',
        ),
        migrations.AlterModelTable(
            name='tr',
            table='cber_schema.tr',
        ),
    ]
