# Generated by Django 4.2.23 on 2025-08-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_c_table_alter_clientcity_table_alter_cs_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='c',
            table='c',
        ),
        migrations.AlterModelTable(
            name='clientcity',
            table='clients_city',
        ),
        migrations.AlterModelTable(
            name='cs',
            table='cs',
        ),
        migrations.AlterModelTable(
            name='dog',
            table='core_dog',
        ),
        migrations.AlterModelTable(
            name='so',
            table='so',
        ),
        migrations.AlterModelTable(
            name='tr',
            table='tr',
        ),
    ]
